from typing import Literal

from common_read_and_write_functions import this_is_write_error, write_holding_register
from func_print_console_and_write_file import print_error, print_text_grey
from read_messages import read_new_messages
