from time import sleep

from probably_not_used.TCP_Client import connect_client, close_client, client
from encode_and_decode import (encode_float,
                             decode_float,
                             encode_int,
                             decode_int,
                             decoder_bits,
                             )
from wrappers import reset_initial_values
# sleep(5)
from read_and_write_functions import (
    write_holding_registers,
    write_holding_register,
    read_holding_registers,
    this_is_write_error,
    read_coils,
    write_coil,
    read_float
)
from read_stutuses_and_message import (
    read_status1_one_bit,
    read_all_messages,
    read_new_messages,
    read_PanelMode,
    read_PanelState,
    read_PanelAlm_one_bit,
    read_status2_one_bit
)
from constants_FB_AP import (
    REGISTERS_AND_VALUE_WRITE_FOR_BEGIN_TEST as LEGS,
    OUT_REGISTER,
    STATUS1
)
from assist_function import switch_position, reset_CmdOp, switch_position_for_legs

connect_client()
old_messages=read_all_messages()
this_is_write_error(address=40101, value=True)
print(read_status1_one_bit(7))
print(read_status2_one_bit(0))
print(read_PanelAlm_one_bit(0))
print(read_new_messages(old_messages))
old_messages=read_all_messages()
this_is_write_error(address=40101, value=False)
print(read_status1_one_bit(7))
print(read_status2_one_bit(0))
print(read_PanelAlm_one_bit(0))
print(read_new_messages(old_messages))
print()
old_messages=read_all_messages()
this_is_write_error(address=40102, value=True)
print(read_status1_one_bit(7))
print(read_status2_one_bit(0))
print(read_PanelAlm_one_bit(0))
print(read_new_messages(old_messages))
old_messages=read_all_messages()
this_is_write_error(address=40102, value=False)
print(read_status1_one_bit(7))
print(read_status2_one_bit(0))
print(read_PanelAlm_one_bit(0))
print(read_new_messages(old_messages))
print()
old_messages=read_all_messages()
this_is_write_error(address=40103, value=True)
print(read_status1_one_bit(7))
print(read_status2_one_bit(0))
print(read_PanelAlm_one_bit(0))
print(read_new_messages(old_messages))
old_messages=read_all_messages()
this_is_write_error(address=40103, value=False)
print(read_status1_one_bit(7))
print(read_status2_one_bit(0))
print(read_PanelAlm_one_bit(0))
print(read_new_messages(old_messages))
print()
#old_messages=read_all_messages()
#switch_position_for_legs(command='ChFlt', required_bool_value=False)
## print(read_status1_one_bit(7))
## print(read_status2_one_bit(0))
#print(read_PanelAlm_one_bit(0))
#print(read_new_messages(old_messages))
#print()
#old_messages=read_all_messages()
#switch_position_for_legs(command='ChFlt', required_bool_value=True)
## print(read_status1_one_bit(7))
## print(read_status2_one_bit(0))
#print(read_PanelAlm_one_bit(0))
#print(read_new_messages(old_messages))
#old_messages=read_all_messages()
#switch_position_for_legs(command='ChFlt', required_bool_value=False)
## print(read_status1_one_bit(7))
## print(read_status2_one_bit(0))
#print(read_PanelAlm_one_bit(0))
#print(read_new_messages(old_messages))
#print()
#old_messages=read_all_messages()
#switch_position_for_legs(command='ChFlt', required_bool_value=True)
## print(read_status1_one_bit(7))
## print(read_status2_one_bit(0))
#print(read_PanelAlm_one_bit(0))
#print(read_new_messages(old_messages))
#old_messages=read_all_messages()
#switch_position_for_legs(command='ChFlt', required_bool_value=False)
## print(read_status1_one_bit(7))
## print(read_status2_one_bit(0))
#print(read_PanelAlm_one_bit(0))
#print(read_new_messages(old_messages))
#print()
#old_messages=read_all_messages()
#switch_position_for_legs(command='ChFlt', required_bool_value=True)
## print(read_status1_one_bit(7))
## print(read_status2_one_bit(0))
#print(read_PanelAlm_one_bit(0))
#print(read_new_messages(old_messages))
#old_messages=read_all_messages()
#switch_position_for_legs(command='ChFlt', required_bool_value=False)
## print(read_status1_one_bit(7))
## print(read_status2_one_bit(0))
#print(read_PanelAlm_one_bit(0))
#print(read_new_messages(old_messages))
#print()
#old_messages=read_all_messages()
#switch_position_for_legs(command='ChFlt', required_bool_value=True)
## print(read_status1_one_bit(7))
## print(read_status2_one_bit(0))
#print(read_PanelAlm_one_bit(0))
#print(read_new_messages(old_messages))
#old_messages=read_all_messages()
#switch_position_for_legs(command='ChFlt', required_bool_value=False)
## print(read_status1_one_bit(7))
## print(read_status2_one_bit(0))
#print(read_PanelAlm_one_bit(0))
#print(read_new_messages(old_messages))
#print()
#old_messages=read_all_messages()
#switch_position_for_legs(command='ChFlt', required_bool_value=True)
## print(read_status1_one_bit(7))
## print(read_status2_one_bit(0))
#print(read_PanelAlm_one_bit(0))
#print(read_new_messages(old_messages))
#old_messages=read_all_messages()
#switch_position_for_legs(command='ChFlt', required_bool_value=False)
## print(read_status1_one_bit(7))
## print(read_status2_one_bit(0))
#print(read_PanelAlm_one_bit(0))
#print(read_new_messages(old_messages))
#print()
#old_messages=read_all_messages()
#switch_position_for_legs(command='ChFlt', required_bool_value=True)
## print(read_status1_one_bit(7))
## print(read_status2_one_bit(0))
#print(read_PanelAlm_one_bit(0))
#print(read_new_messages(old_messages))
#old_messages=read_all_messages()
#switch_position_for_legs(command='ChFlt', required_bool_value=False)
## print(read_status1_one_bit(7))
## print(read_status2_one_bit(0))
#print(read_PanelAlm_one_bit(0))
#print(read_new_messages(old_messages))
#print()
#old_messages=read_all_messages()
#switch_position_for_legs(command='ChFlt', required_bool_value=True)
## print(read_status1_one_bit(7))
## print(read_status2_one_bit(0))
#print(read_PanelAlm_one_bit(0))
#print(read_new_messages(old_messages))
#old_messages=read_all_messages()
#switch_position_for_legs(command='ChFlt', required_bool_value=False)
## print(read_status1_one_bit(7))
## print(read_status2_one_bit(0))
#print(read_PanelAlm_one_bit(0))
#print(read_new_messages(old_messages))
#print()
#old_messages=read_all_messages()
#switch_position_for_legs(command='ChFlt', required_bool_value=True)
## print(read_status1_one_bit(7))
## print(read_status2_one_bit(0))
#print(read_PanelAlm_one_bit(0))
#print(read_new_messages(old_messages))
#old_messages=read_all_messages()
#switch_position_for_legs(command='ChFlt', required_bool_value=False)
## print(read_status1_one_bit(7))
## print(read_status2_one_bit(0))
#print(read_PanelAlm_one_bit(0))
#print(read_new_messages(old_messages))
#print()
#old_messages=read_all_messages()
#switch_position_for_legs(command='ChFlt', required_bool_value=True)
## print(read_status1_one_bit(7))
## print(read_status2_one_bit(0))
#print(read_PanelAlm_one_bit(0))
#print(read_new_messages(old_messages))
#old_messages=read_all_messages()
#switch_position_for_legs(command='ChFlt', required_bool_value=False)
## print(read_status1_one_bit(7))
## print(read_status2_one_bit(0))
#print(read_PanelAlm_one_bit(0))
#print(read_new_messages(old_messages))
#print()
# switch_position_for_legs(command='AHLimEn', required_bool_value=True)
# write_holding_register(address=801, value=4)
# sleep(5)
# while True:
# write_holding_registers(address=40500, values=12)
# old_messages = read_all_messages()
# write_holding_registers(address=40500, values=19)
# print(read_new_messages(old_messages))
# switch_position_for_legs(command='AlarmOff', required_bool_value=True)
# write_holding_registers(address=40500, values=12)
# old_messages = read_all_messages()
# write_holding_registers(address=40500, values=19)
# print(read_new_messages(old_messages))
print()



close_client()